---
# file: roles/maven/tasks/main.yml
# role for installing maven on a slave

- name: "make sure download dir exists"
  file:
    dest="{{ item.download_dir }}"
    state="directory"
    owner="{{ user }}"
    group="{{ group }}"
  with_items: mvns_to_install

- name: "make sure install dir exists"
  file:
    dest="{{ item.install_dir }}"
    state="directory"
    owner="{{ user }}"
    group="{{ group }}"
  with_items: mvns_to_install

- name: "download maven"
  get_url:
    url="http://archive.apache.org/dist/maven/binaries/{{ item.package_name }}"
    dest="{{ item.download_dir }}/{{ item.package_name }}"
  with_items: mvns_to_install

- name: "extract maven"
  sudo: "yes"
  sudo_user: "{{ user }}"
  unarchive:
    src="{{ item.download_dir }}/{{ item.package_name }}"
    dest="{{ item.install_dir }}"
    copy="false"
  args:
    creates: "{{ item.install_dir }}/{{ item.extract_name }}"
  with_items: mvns_to_install

- name: "rename maven folder"
  command: "mv {{ item.extract_name }} {{ item.install_name }}"
  args:
    chdir: "{{ item.install_dir }}"
  with_items: mvns_to_install

- name: "remove install files"
  file:
    dest="{{ item.download_dir }}"
    state="absent"
  with_items: mvns_to_install
