---
# file: build-images.yml
# main play for building docker images on a docker host
# use "-i localhost" and "-c local" for building on local machine

- name: "a play that builds a set of docker images"
  hosts: "docker"
  gather_facts: "yes"
  connection: "local"

  vars_files:
  - vars/main.yml

  roles:
  - { role: dockerfile-generator, images_to_build: "{{ available_images }}" }
  - { role: playbook-generator, images_to_build: "{{ available_images }}" }
  - { role: image-builder,
        images_to_build: "{{ available_images }}",
        push_images: "{{ docker_push_images }}" }
