---
# file: jenkins-slave-selenium/setup.yml
# main play for setting up jenkins-slave-selenium
# use "-i localhost" and "-c local" for building on local machine

- name: "play that setups jenkins-slave-selenium"
  hosts: "local"
  connection: "local"

  vars:
    jenkins_user:   "jenkins"
    jenkins_group:  "jenkins"
    repo_google_all:
      - chrome

  pre_tasks:
  - file:
      dest: /opt/firefox
      state: absent

  roles:
  - { role: firefox, firefox_pkg_version: 24.2.0esr }

